/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  UserSession,
} from '@esri/arcgis-rest-auth';


export namespace Components {

  interface HubFollowButton {
    /**
    * ClientID that identifies the app launching OAuth 2.0
    */
    'clientid': string;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'initiativeid': string;
    /**
    * User metadata
    */
    'user': UserSession;
  }
  interface HubFollowButtonAttributes extends StencilHTMLAttributes {
    /**
    * ClientID that identifies the app launching OAuth 2.0
    */
    'clientid'?: string;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'initiativeid'?: string;
    /**
    * User metadata
    */
    'user'?: UserSession;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HubFollowButton': Components.HubFollowButton;
  }

  interface StencilIntrinsicElements {
    'hub-follow-button': Components.HubFollowButtonAttributes;
  }


  interface HTMLHubFollowButtonElement extends Components.HubFollowButton, HTMLStencilElement {}
  var HTMLHubFollowButtonElement: {
    prototype: HTMLHubFollowButtonElement;
    new (): HTMLHubFollowButtonElement;
  };

  interface HTMLElementTagNameMap {
    'hub-follow-button': HTMLHubFollowButtonElement
  }

  interface ElementTagNameMap {
    'hub-follow-button': HTMLHubFollowButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
