/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  UserSession,
} from '@esri/arcgis-rest-auth';
import {
  IUser,
} from '@esri/arcgis-rest-common-types';


export namespace Components {

  interface HubEventDetails {
    'attending': boolean;
    /**
    * ClientID to identify the app launching OAuth
    */
    'clientid': string;
    'eventDate': string;
    'eventGroupId': string;
    'eventOrganizer': JSX.Element;
    'eventServiceUrl': string;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'eventtitle': string;
    /**
    * url of the ArcGIS Online organization
    */
    'orgurl': string;
    /**
    * Authentication info.
    */
    'session': UserSession;
  }
  interface HubEventDetailsAttributes extends StencilHTMLAttributes {
    'attending'?: boolean;
    /**
    * ClientID to identify the app launching OAuth
    */
    'clientid'?: string;
    'eventDate'?: string;
    'eventGroupId'?: string;
    'eventOrganizer'?: JSX.Element;
    'eventServiceUrl'?: string;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'eventtitle'?: string;
    /**
    * url of the ArcGIS Online organization
    */
    'orgurl'?: string;
    /**
    * Authentication info.
    */
    'session'?: UserSession;
  }

  interface HubFollowInitiative {
    /**
    * ClientID to identify the app launching auth
    */
    'clientid': string;
    /**
    * Denotes whether the user is already following the configured initiative.
    */
    'following': boolean;
    /**
    * Follow icon
    */
    'icon': JSX.Element;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'initiativeid': string;
    /**
    * url of the ArcGIS Online organization
    */
    'orgurl': string;
    /**
    * Authentication info.
    */
    'session': UserSession;
    /**
    * User metadata
    */
    'user': IUser;
  }
  interface HubFollowInitiativeAttributes extends StencilHTMLAttributes {
    /**
    * ClientID to identify the app launching auth
    */
    'clientid'?: string;
    /**
    * Denotes whether the user is already following the configured initiative.
    */
    'following'?: boolean;
    /**
    * Follow icon
    */
    'icon'?: JSX.Element;
    /**
    * identifier for the ArcGIS Hub initiative
    */
    'initiativeid'?: string;
    /**
    * url of the ArcGIS Online organization
    */
    'orgurl'?: string;
    /**
    * Authentication info.
    */
    'session'?: UserSession;
    /**
    * User metadata
    */
    'user'?: IUser;
  }

  interface HubButton {
    /**
    * action to trigger when the button is clicked
    */
    'action': Function;
    /**
    * Icon to display alonside the text
    */
    'icon': JSX.Element;
    /**
    * Button text to display
    */
    'text': string;
  }
  interface HubButtonAttributes extends StencilHTMLAttributes {
    /**
    * action to trigger when the button is clicked
    */
    'action'?: Function;
    /**
    * Icon to display alonside the text
    */
    'icon'?: JSX.Element;
    /**
    * Button text to display
    */
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HubEventDetails': Components.HubEventDetails;
    'HubFollowInitiative': Components.HubFollowInitiative;
    'HubButton': Components.HubButton;
  }

  interface StencilIntrinsicElements {
    'hub-event-details': Components.HubEventDetailsAttributes;
    'hub-follow-initiative': Components.HubFollowInitiativeAttributes;
    'hub-button': Components.HubButtonAttributes;
  }


  interface HTMLHubEventDetailsElement extends Components.HubEventDetails, HTMLStencilElement {}
  var HTMLHubEventDetailsElement: {
    prototype: HTMLHubEventDetailsElement;
    new (): HTMLHubEventDetailsElement;
  };

  interface HTMLHubFollowInitiativeElement extends Components.HubFollowInitiative, HTMLStencilElement {}
  var HTMLHubFollowInitiativeElement: {
    prototype: HTMLHubFollowInitiativeElement;
    new (): HTMLHubFollowInitiativeElement;
  };

  interface HTMLHubButtonElement extends Components.HubButton, HTMLStencilElement {}
  var HTMLHubButtonElement: {
    prototype: HTMLHubButtonElement;
    new (): HTMLHubButtonElement;
  };

  interface HTMLElementTagNameMap {
    'hub-event-details': HTMLHubEventDetailsElement
    'hub-follow-initiative': HTMLHubFollowInitiativeElement
    'hub-button': HTMLHubButtonElement
  }

  interface ElementTagNameMap {
    'hub-event-details': HTMLHubEventDetailsElement;
    'hub-follow-initiative': HTMLHubFollowInitiativeElement;
    'hub-button': HTMLHubButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
