/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HubFollowButton {
    /**
    * The first name
    */
    'clientid': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface HubFollowButtonAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'clientid'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HubFollowButton': Components.HubFollowButton;
  }

  interface StencilIntrinsicElements {
    'hub-follow-button': Components.HubFollowButtonAttributes;
  }


  interface HTMLHubFollowButtonElement extends Components.HubFollowButton, HTMLStencilElement {}
  var HTMLHubFollowButtonElement: {
    prototype: HTMLHubFollowButtonElement;
    new (): HTMLHubFollowButtonElement;
  };

  interface HTMLElementTagNameMap {
    'hub-follow-button': HTMLHubFollowButtonElement
  }

  interface ElementTagNameMap {
    'hub-follow-button': HTMLHubFollowButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
